### ISSUE TITLE
write unit tests for the SCRCdataAPI package

### ISSUE THREAD

**Issue by soniamitchell** [ScottishCovidResponse/SCRCdataAPI#18]

**Comment by RyanJField** [comment]
List of exported functions:

| Number | Function | Unit Test Complete (Y/N) | Who is Responsible for Test |
| --- | --- | --- | --- |
| 1 | attach_issue | N | |
| 2 | bin_ages | N | |
| 3 | check_exists | N | |
| 4 | clean_query | N | |
| 5 | convert_url | N | |
| 6 | create_array | Y | |
| 7 | create_distribution | Y | |
| 8 | create_estimate | Y | |
| 9 | create_table | Y | |
| 10 | create_version_number | N | |
| 11 | download_from_database | N | |
| 12 | file_structure | Y | @RyanJField  |
| 13 | get_entity | N | |
| 14 | get_entry | N | |
| 15 | get_existing | N | |
| 16 | get_github_hash | N | |
| 17 | get_h5_from_object_id | N | |
| 18 | get_hash | N | |
| 19 | get_storage_location | N | |
| 20 | get_url | N | |
| 21 | new_author | N | |
| 22 | new_code_repo_release | N | |
| 23 | new_coderun | N | |
| 24 | new_data_product | N | |
| 25 | new_external_object | N | |
| 26 | new_issue | N | |
| 27 | new_keyword | N | |
| 28 | new_namespace | N | |
| 29 | new_object | N | |
| 30 | new_object_component | N | |
| 31 | new_source | N | |
| 32 | new_storage_location | N | |
| 33 | new_storage_root | N | |
| 34 | new_text_file | N | |
| 35 | paper_exists | N | |
| 36 | post_data | N | |
| 37 | read_array | N | |
| 38 | read_estimate | N | |
| 39 | read_table | N | |
| 40 | upload_data_product | N | |
| 41 | upload_github_repo | N | |
| 42 | upload_object_links | N | |
| 43 | upload_paper | N | |
| 44 | upload_source_data | N | |
| 45 | upload_submission_script | N | |

Other Functions that require testing:
# Coming soon
